[package]
name = "chapter-03"
version = "0.1.0"
authors = ["Rodrigo Casara <rodrigocasara@gmail.com>"]
edition = "2018"
readme = "README.md"

[dependencies]

[dev-dependencies]
pretty_assertions = "0.6.1"

[[example]]
name = "generate_tax_invoice"
path = "examples/generate.rs"
